[package]
name = "roles_types"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "roles_types"

[dependencies]
hdi = { workspace = true }
holo_hash = { version = "0.4.0-rc", features = ["encoding"] }

serde = { workspace = true }
