[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = ["zomes/coordinator/*", "zomes/integrity/*", "crates/*"]
resolver = "2"

[workspace.dependencies]
hdi = "0.5.1"
hdk = { version = "0.4.1", features = [ "unstable-functions" ] }
serde = "1"

