name: "Build and cache zomes"
on:
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build-and-cache-zomes:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Extend space
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: ./.github/actions/extend-space

      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-24.05

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-open-dev

      - uses: cachix/cachix-action@v15
        with:
          name: darksoil-studio

      - name: Install and test
        run: |
          nix develop --no-update-lock-file --accept-flake-config --command bash -c "pnpm i && pnpm t && pnpm -F @darksoil-studio/roles-zome build"

      - name: Build debug zomes
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.DARKSOIL_CACHIX_AUTH_TOKEN }}"
        run: |
          cachix watch-exec darksoil-studio -- nix build --no-update-lock-file --accept-flake-config -L .#roles_integrity.meta.debug
          cachix push darksoil-studio $(nix path-info --json --accept-flake-config --no-warn-dirty .#roles_integrity.meta.debug | nix run nixpkgs#jq -- -r 'keys[0]')

          cachix watch-exec darksoil-studio -- nix build --no-update-lock-file --accept-flake-config -L .#roles.meta.debug
          cachix push darksoil-studio $(nix path-info --json --accept-flake-config --no-warn-dirty .#roles.meta.debug | nix run nixpkgs#jq -- -r 'keys[0]')

      - name: Pin debug zomes
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.DARKSOIL_CACHIX_AUTH_TOKEN }}"
        run: |
          cachix pin darksoil-studio roles_integrity_debug $(nix path-info --json --accept-flake-config --no-warn-dirty .#roles_integrity.meta.debug | nix run nixpkgs#jq -- -r 'keys[0]')

          cachix pin darksoil-studio roles_debug $(nix path-info --json --accept-flake-config --no-warn-dirty .#roles.meta.debug | nix run nixpkgs#jq -- -r 'keys[0]')

      - name: Build release zomes
        if: matrix.os == 'ubuntu-latest'
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.DARKSOIL_CACHIX_AUTH_TOKEN }}"
        run: |
          cachix watch-exec darksoil-studio -- nix build --no-update-lock-file --accept-flake-config -L .#roles_integrity
          cachix push darksoil-studio $(nix path-info --json --accept-flake-config --no-warn-dirty .#roles_integrity | nix run nixpkgs#jq -- -r 'keys[0]')

          cachix watch-exec darksoil-studio -- nix build --no-update-lock-file --accept-flake-config -L .#roles
          cachix push darksoil-studio $(nix path-info --json --accept-flake-config --no-warn-dirty .#roles | nix run nixpkgs#jq -- -r 'keys[0]')

      - name: Build release zomes
        if: matrix.os == 'ubuntu-latest' && github.event_name != 'pull_request' && github.ref_name == 'main'
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.DARKSOIL_CACHIX_AUTH_TOKEN }}"
        run: |
          cachix pin darksoil-studio roles_integrity $(nix path-info --json --accept-flake-config --no-warn-dirty .#roles_integrity | nix run nixpkgs#jq -- -r 'keys[0]')

          cachix pin darksoil-studio roles $(nix path-info --json --accept-flake-config --no-warn-dirty .#roles | nix run nixpkgs#jq -- -r 'keys[0]')
